# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonsTemplateCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=30)),
                ('action1class', models.CharField(max_length=30)),
                ('action1id', models.CharField(max_length=10)),
                ('action2class', models.CharField(max_length=30)),
                ('action2id', models.CharField(max_length=10)),
                ('action3class', models.CharField(max_length=30)),
                ('action3id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselColumnCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=30)),
                ('thumbnail_image_url', models.CharField(max_length=50)),
                ('action1class', models.CharField(max_length=30)),
                ('action1id', models.CharField(max_length=10)),
                ('action2class', models.CharField(max_length=30)),
                ('action2id', models.CharField(max_length=10)),
                ('action3class', models.CharField(max_length=30)),
                ('action3id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselTemplateCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('CarouselColumn1id', models.CharField(max_length=10)),
                ('CarouselColumn2id', models.CharField(max_length=10)),
                ('CarouselColumn3id', models.CharField(max_length=10)),
                ('CarouselColumn4id', models.CharField(max_length=10)),
                ('CarouselColumn5id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCarouselTemplateCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=50)),
                ('action1class', models.CharField(max_length=30)),
                ('action1id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSendMessageCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('original_content_url', models.CharField(max_length=50)),
                ('preview_image_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplateActionCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PostbackTemplateActionCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StickerSendMessageCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('package_id', models.IntegerField()),
                ('sticker_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateSendMessageCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('alt_text', models.CharField(max_length=20)),
                ('templateclass', models.CharField(max_length=30)),
                ('templateid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TextSendMessageCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='URITemplateActionCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
